name: ESLint Check

on:
  - push

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ['17.x', '18.x']

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js (${{ matrix.node-version }}) Environment
      uses: actions/setup-node@v3.1.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Node Dependencies and run eslint
      run: |
        npm i -g eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser
        eslint .
